# Generated by Django 2.2.26 on 2022-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('day', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
